sudo: required
services:
  - docker  #run docker first

before_install:
  - docker build -t kulbhushansaxena/docker-react -f Dockerfile.dev .     #build the image

script:
  - docker run kulbhushansaxena/docker-react npm run test -- --coverage   #Scripts which travs checks is sccessfull or not